name: Sync vps.txt

on:
  push:
    paths:
      - "serv00-public.txt"
      - "oracle-public.txt"

jobs:
  update-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge files
        run: cat serv00-public.txt oracle-public.txt > vps.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add vps.txt
          git commit -m "Auto-update vps.txt from serv00-public.txt and oracle-public.txt" || exit 0
          git push
