name: Handle lunes.txt changes — split lunes and update stations

on:
  push:
    paths:
      - 'lunes.txt'

permissions:
  contents: write

jobs:
  split-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout linkcode repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create lunes-vless/vmess/trojan from lunes.txt
        run: |
          sed -n '1,3p' lunes.txt > lunes-vless.txt
          sed -n '4,6p' lunes.txt > lunes-vmess.txt
          sed -n '7,9p' lunes.txt > lunes-trojan.txt
          git add lunes-vless.txt lunes-vmess.txt lunes-trojan.txt
          if git diff --cached --quiet; then
            echo "No changes to lunes-xxx files"
          else
            git commit -m "chore: generate lunes-vless/vmess/trojan from lunes.txt"
            git push

      - name: Build stations content
        run: |
          cat lunes.txt > combined_stations.txt
          echo "" >> combined_stations.txt
          cat niclai-station.txt >> combined_stations.txt

      - name: Clone target repo and update stations.txt
        env:
          PAT: ${{ secrets.LAIJUNLING_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          rm -rf youtubedownloader || true
          git clone https://x-access-token:${PAT}@github.com/laijunling/youtubedownloader.git
          cd youtubedownloader
          cp ../combined_stations.txt stations.txt
          git add stations.txt
          if git diff --cached --quiet; then
            echo "No changes to stations.txt"
            exit 0
          fi
          git commit -m "chore: update stations.txt from linkcode (lunes.txt changed)"
          git push origin HEAD
