name: Handle lunes.txt changes — update stations

on:
  push:
    paths:
      - 'lunes.txt'

permissions:
  contents: write

jobs:
  sync-and-update:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout main repo
      - name: Checkout linkcode repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Configure Git identity
      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      # 3️⃣ Sync lunes.txt -> A-lunes.txt
      - name: Sync A-lunes.txt with lunes.txt
        run: |
          #!/bin/bash
          set -e
          if [ ! -f lunes.txt ]; then
            echo "❌ lunes.txt not found!"
            exit 1
          fi
          cp lunes.txt A-lunes.txt
          git add A-lunes.txt
          if git diff --cached --quiet; then
            echo "A-lunes.txt already up to date"
          else
            git commit -m "chore: sync A-lunes.txt with lunes.txt"
            git push
          fi

      # 3️⃣ Generate lunes-vless/vmess/trojan files
      - name: Create lunes-vless/vmess/trojan from lunes.txt
        run: |
          #!/bin/bash
          set -e
          if [ ! -f lunes.txt ]; then
            echo "lunes.txt not found!" >&2
            exit 1
          fi
          sed -n '1,3p' lunes.txt > lunes-vless.txt
          sed -n '4,6p' lunes.txt > lunes-vmess.txt
          sed -n '7,9p' lunes.txt > lunes-trojan.txt
          git add lunes-vless.txt lunes-vmess.txt lunes-trojan.txt
          if git diff --cached --quiet; then
            echo "No changes to lunes-xxx files"
          else
            git commit -m "chore: generate lunes-vless/vmess/trojan from lunes.txt"
            git push
          fi

      # 4️⃣ Build combined_stations.txt
      - name: Build combined stations content
        run: |
          #!/bin/bash
          set -e
          if [ ! -f stations.txt ]; then
            echo "stations.txt not found!" >&2
            exit 1
          fi
          cat lunes.txt > combined_stations.txt
          cat stations.txt >> combined_stations.txt
          echo "✅ combined_stations.txt built."

      # 5️⃣ Update ytd repo
      - name: Update stations in ytd repo
        env:
          PAT: ${{ secrets.LAIJUNLING_PAT }}
        run: |
          #!/bin/bash
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          rm -rf ytd || true
          git clone https://x-access-token:${PAT}@github.com/laijunling/ytd.git
          cd ytd
          cp ../combined_stations.txt stations.txt
          cp ../combined_stations.txt nodes.txt
          git add stations.txt nodes.txt
          if git diff --cached --quiet; then
            echo "✅ No changes for ytd"
          else
            git commit -m "chore: update stations.txt nodes.txt from linkcode (lunes.txt changed)"
            git pull --rebase origin HEAD || true
            git push origin HEAD
          fi
          cd ..

      # 6️⃣ Update iron repo
      - name: Update stations & sacd2868.txt in iron repo
        env:
          PAT: ${{ secrets.LAIJUNLING_PAT }}
        run: |
          #!/bin/bash
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          rm -rf iron || true
          git clone https://x-access-token:${PAT}@github.com/laijunling/iron.git
          cd iron
          cp ../combined_stations.txt stations.txt
          cp ../combined_stations.txt nodes.txt
          cp ../combined_stations.txt iron.txt
          cp ../combined_stations.txt lagon.txt
          last_line=$(tail -n 1 ../combined_stations.txt)
          echo "$last_line" > sacd2868.txt
          git add stations.txt nodes.txt iron.txt lagon.txt sacd2868.txt
          if git diff --cached --quiet; then
            echo "✅ No changes for iron"
          else
            git commit -m "chore: sync combined_stations & sacd2868.txt from linkcode (lunes.txt changed)"
            git pull --rebase origin HEAD || true
            git push origin HEAD
          fi
          cd ..

      # 7️⃣ Update team repo
      - name: Update stations & sacd2868.txt in team repo
        env:
          PAT: ${{ secrets.LAIJUNLING_PAT }}
        run: |
          #!/bin/bash
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          rm -rf team || true
          git clone https://x-access-token:${PAT}@github.com/laijunling/team.git
          cd team
          cp ../combined_stations.txt stations.txt
          cp ../combined_stations.txt nodes.txt
          cp ../combined_stations.txt iron.txt
          cp ../combined_stations.txt lagon.txt
          last_line=$(tail -n 1 ../combined_stations.txt)
          echo "$last_line" > sacd2868.txt
          git add stations.txt nodes.txt iron.txt lagon.txt sacd2868.txt
          if git diff --cached --quiet; then
            echo "✅ No changes for team"
          else
            git commit -m "chore: sync combined_stations & sacd2868.txt from linkcode (lunes.txt changed)"
            git pull --rebase origin HEAD || true
            git push origin HEAD
          fi
          cd ..
